[package]
name = "a02_woodeneye_008"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sdl3 = { version = "0", features = [] }

[dependencies.sdl3-sys]
version = "0.1.3+SDL3-preview-3.1.6"
