[package]
name = "a10_geometry"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl3 = { version = "0", features = ["unsafe_textures", "gfx"] }

[dependencies.sdl3-sys]
version = "0.1.3+SDL3-preview-3.1.6"
