[package]
name = "raw-windows-handle-with-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
pollster = "0.4.0"
sdl2 = { version = "0.37.0", features = ["raw-window-handle"] }
wgpu = { version = "0.20", features = ["spirv"] }
