[package]
name = "cursor_sdl2"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.37.0", features = ["image"] }
bitflags = "1.2.1"
libc = "0.2.92"
lazy_static = "1.4.0"
sdl2-sys = "0.37.0"
