[package]
name = "a06_textures_lifetime_solution_final"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl3 = { version = "0", features = ["unsafe_textures"] }

[dependencies.sdl3-sys]
version = "0.1.3+SDL3-preview-3.1.6"

